### ISSUE TITLE
Error when using getDbExposureData

### ISSUE THREAD

**Issue by rfherrerac** [OHDSI/CaseControl#1]
Dear all, 
When trying to use the getDbExposureData, it returns an error: 

‘R.utils’ must be installed for this functionality.
Would you like to install it?

This is my configuration
Package CaseControl version 3.0.0

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

Any help, I will appreciate it.

**Comment by schuemie** [comment]
I'm sorry. This package is no longer supported. I've just updated the README to mention this. 

I recommend reading [this paper](https://onlinelibrary.wiley.com/doi/full/10.1002/sim.8215)
